---
- name: Deployment on web server
  hosts: all
  become: yes
  become_method: sudo
  vars:
    - db_name: drupal
    - db_user: drupal_user
    - db_password: 1q2w3e4r5t6y7u8i
  roles:
     - webserver